# Top-level configuration
name = "retromatch-game-info"
main = "workers/scrape.ts"
compatibility_date = "2023-10-30"

node_compat = true
workers_dev = true

kv_namespaces = [
    { binding = "retromatch", id = "aea225476eec4b6bb1f617e892cc02c2", preview_id = "aea225476eec4b6bb1f617e892cc02c2" },
]
[[r2_buckets]]
binding = 'IMAGES_BUCKET'
preview_bucket_name = "retromatch"
bucket_name = 'retromatch'
