# Top-level configuration
name = "retromatch-game-info"
main = "workers/scrape.ts"
compatibility_date = "2023-12-20"

workers_dev = false
route = { pattern = "example.org/*", zone_name = "example.org" }

kv_namespaces = [
    { binding = "retromatch", id = "aea225476eec4b6bb1f617e892cc02c2" }
]
