export const consoles = [
  {
    name: "3DO Interactive Multiplayer",
    folderNames: { emulationStation: ["3DO"], miyoo: ["PANASONIC"] },
    extensions: [".bin", ".chd", ".cue", ".iso", ".7z", ".zip"],
  },
  {
    name: "Adventure Game Studio Game Engine",
    folderNames: { emulationStation: ["ags"] },
    extensions: [".desktop", ".sh"],
  },
  {
    name: "Commodore Amiga",
    folderNames: { emulationStation: ["amiga"], miyoo: ["AMIGA"] },
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Commodore Amiga 1200",
    folderNames: { emulationStation: ["amiga1200"], miyoo: ["AMIGA"] },
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Commodore Amiga 600",
    folderNames: { emulationStation: ["amiga600"], miyoo: ["AMIGA"] },
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Commodore Amiga CD32",
    folderNames: { emulationStation: ["amigacd32"], miyoo: ["AMIGACD"] },
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Amstrad CPC",
    folderNames: { emulationStation: ["amstradcpc"], miyoo: ["CPC"] },
    extensions: [
      ".cdt",
      ".cpr",
      ".dsk",
      ".kcr",
      ".m3u",
      ".sna",
      ".tap",
      ".voc",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Google Android",
    folderNames: { emulationStation: ["android"] },
    extensions: ["apk", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Apple II",
    folderNames: { emulationStation: ["apple2"] },
    extensions: [".do", ".dsk", ".nib", ".po"],
  },
  {
    name: "Apple IIGS",
    folderNames: { emulationStation: ["apple2gs"] },
    extensions: [".2mg"],
  },
  {
    name: "Arcade",
    folderNames: { emulationStation: ["arcade"], miyoo: ["ARCADE"] },
    extensions: [
      ".cmd",
      ".CMD",
      ".desktop",
      ".sh",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Emerson Arcadia 2001",
    folderNames: { emulationStation: ["arcadia"] },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Arduboy Miniature Game System",
    folderNames: { emulationStation: ["arduboy"] },
    extensions: [".hex", ".7z", ".zip"],
  },
  {
    name: "Bally Astrocade",
    folderNames: { emulationStation: ["astrocde"] },
    extensions: [".7z", ".zip"],
  },
  {
    name: "Atari 2600",
    folderNames: { emulationStation: ["atari2600"], miyoo: ["ATARI"] },
    extensions: [".a26", ".bin", ".7z", ".zip"],
  },
  {
    name: "Atari 5200",
    folderNames: {
      emulationStation: ["atari5200"],
      miyoo: ["FIFTYTWOHUNDRED"],
    },
    extensions: [
      ".a52",
      ".atr",
      ".atx",
      ".bin",
      ".car",
      ".cas",
      ".cdm",
      ".rom",
      ".xex",
      ".xfd",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Atari 7800 ProSystem",
    folderNames: {
      emulationStation: ["atari7800"],
      miyoo: ["SEVENTYEIGHTHUNDRED"],
    },
    extensions: [".a78", ".bin", ".7z", ".zip"],
  },
  {
    name: "Atari 800",
    folderNames: { emulationStation: ["atari800"], miyoo: ["EIGHTHUNDRED"] },
    extensions: [
      ".a52",
      ".atr",
      ".atx",
      ".bin",
      ".car",
      ".cas",
      ".cdm",
      ".rom",
      ".xex",
      ".xfd",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Atari Jaguar",
    folderNames: {
      emulationStation: ["atarijaguar"],
      miyoo: ["JAGUAR"],
    },
    extensions: [
      ".abs",
      ".bin",
      ".cdi",
      ".cof",
      ".cue",
      ".j64",
      ".jag",
      ".prg",
      ".rom",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Atari Jaguar CD",
    folderNames: {
      emulationStation: ["atarijaguarcd"],
    },
    extensions: [".7z", ".zip"],
  },
  {
    name: "Atari Lynx",
    folderNames: {
      emulationStation: ["atarilynx"],
      miyoo: ["LYNX"],
    },
    extensions: [".lnx", ".o", ".7z", ".zip"],
  },
  {
    name: "Atari ST",
    folderNames: {
      emulationStation: ["atarist"],
      miyoo: ["ATARIST"],
    },
    extensions: [".st", ".msa", ".stx", ".dim", ".ipf", ".m3u", ".7z", ".zip"],
  },
  {
    name: "Atari XE",
    folderNames: {
      emulationStation: ["atarixe"],
    },
    extensions: [
      ".a52",
      ".atr",
      ".atx",
      ".bin",
      ".cas",
      ".cdm",
      ".xex",
      ".xfd",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Sammy Corporation Atomiswave",
    folderNames: {
      emulationStation: ["atomiswave"],
    },
    extensions: [
      ".bin",
      ".cdi",
      ".cue",
      ".dat",
      ".elf",
      ".gdi",
      ".iso",
      ".lst",
      ".m3u",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Acorn Computers BBC Micro",
    folderNames: {
      emulationStation: ["bbcmicro"],
    },
    extensions: [".dsd", ".img", ".ssd", ".7z", ".zip"],
  },
  {
    name: "Commodore 64",
    folderNames: {
      emulationStation: ["c64"],
      miyoo: ["COMMODORE"],
    },
    extensions: [
      ".bin",
      ".cmd",
      ".crt",
      ".d2m",
      ".d4m",
      ".d64",
      ".d6z",
      ".d71",
      ".d7z",
      ".d80",
      ".d81",
      ".d82",
      ".d8z",
      ".g41",
      ".g4z",
      ".g64",
      ".g6z",
      ".gz",
      ".lnx",
      ".m3u",
      ".nbz",
      ".nib",
      ".p00",
      ".prg",
      ".t64",
      ".tap",
      ".vfl",
      ".vsf",
      ".x64",
      ".x6z",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Cave Story",
    folderNames: {
      emulationStation: ["cavestory"],
    },
    extensions: [".exe", ".7z", ".zip"],
  },
  {
    name: "Philips CD-i",
    folderNames: {
      emulationStation: ["cdimono1"],
    },
    extensions: [".chd", ".cue", ".iso"],
  },
  {
    name: "Commodore CDTV",
    folderNames: {
      emulationStation: ["cdtv"],
    },
    extensions: [
      ".ccd",
      ".chd",
      ".cue",
      ".iso",
      ".m3u",
      ".mds",
      ".nrg",
      ".rp9",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "ChaiLove Game Engine",
    folderNames: {
      emulationStation: ["chailove"],
    },
    extensions: [".chai", ".chailove", ".7z", ".zip"],
  },
  {
    name: "Fairchild Channel F",
    folderNames: {
      emulationStation: ["channelf"],
      miyoo: ["FAIRCHILD"],
    },
    extensions: [".bin", ".chf", ".7z", ".zip"],
  },
  {
    name: "Tandy Color Computer",
    folderNames: {
      emulationStation: ["coco"],
    },
    extensions: [".cas", ".ccc", ".dsk", ".rom"],
  },
  {
    name: "Coleco ColecoVision",
    folderNames: {
      emulationStation: ["colecovision"],
      miyoo: ["COLECO"],
    },
    extensions: [
      ".bin",
      ".cas",
      ".col",
      ".cv",
      ".dsk",
      ".m3u",
      ".mx1",
      ".mx2",
      ".ri",
      ".rom",
      ".sc",
      ".sg",
      ".7z",
      ".zip",
    ],
  },
  {
    name: "Capcom Play System",
    folderNames: {
      emulationStation: ["cps"],
      miyoo: ["CPS"],
    },
    extensions: [".7z", ".zip"],
  },
  {
    name: "Capcom Play System I",
    folderNames: {
      emulationStation: ["cps1"],
      miyoo: ["CPS1"],
    },
    extensions: [".7z", ".zip"],
  },
  {
    name: "Capcom Play System II",
    folderNames: {
      emulationStation: ["cps2"],
      miyoo: ["CPS2"],
    },
    extensions: [".7z", ".zip"],
  },
  {
    name: "Capcom Play System III",
    folderNames: {
      emulationStation: ["cps3"],
      miyoo: ["CPS3"],
    },
    extensions: [".7z", ".zip"],
  },
  {
    name: "VTech CreatiVision",
    folderNames: {
      emulationStation: ["crvision"],
    },
    extensions: [".bin", ".BIN", ".rom", ".ROM", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Adobe Flash",
    folderNames: {
      emulationStation: ["flash"],
    },
    extensions: [".swf", ".SWF"],
  },
  {
    name: "Daphne Arcade LaserDisc Emulator",
    folderNames: {
      emulationStation: ["daphne", "laserdisc"],
      miyoo: "DAPHNE",
    },
    extensions: [
      ".daphne",
      ".ogv",
      ".OGV",
      ".singe",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Doom",
    folderNames: {
      emulationStation: ["doom"],
    },
    extensions: [
      ".desktop",
      ".iwad",
      ".IWAD",
      ".pk4",
      ".PK4",
      ".pwad",
      ".PWAD",
      ".sh",
      ".wad",
      ".WAD",
    ],
  },
  {
    name: "DOS (PC)",
    folderNames: {
      emulationStation: ["dos"],
      miyoo: ["DOS"],
    },
    extensions: [
      ".bat",
      ".BAT",
      ".com",
      ".COM",
      ".conf",
      ".CONF",
      ".cue",
      ".CUE",
      ".dosz",
      ".DOSZ",
      ".exe",
      ".EXE",
      ".iso",
      ".ISO",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Dragon Data Dragon 32",
    folderNames: {
      emulationStation: "dragon32",
    },
    extensions: [
      ".cas",
      ".CAS",
      ".ccc",
      ".CCC",
      ".dsk",
      ".DSK",
      ".rom",
      ".ROM",
    ],
  },
  {
    name: "Sega Dreamcast",
    folderNames: {
      emulationStation: ["dreamcast"],
    },
    extensions: [
      ".cdi",
      ".CDI",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".dat",
      ".DAT",
      ".elf",
      ".ELF",
      ".gdi",
      ".GDI",
      ".iso",
      ".ISO",
      ".lst",
      ".LST",
      ".m3u",
      ".M3U",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "EasyRPG Game Engine",
    folderNames: {
      emulationStation: ["easyrpg"],
      miyoo: ["EASYRPG"],
    },
    extensions: [".easyrpg", ".zip", ".ZIP"],
  },
  {
    name: "NES",
    folderNames: {
      emulationStation: ["nes", "famicom"],
      miyoo: ["FC"],
    },
    extensions: [
      ".3dsen",
      ".3DSEN",
      ".fds",
      ".FDS",
      ".nes",
      ".NES",
      ".unf",
      ".UNF",
      ".unif",
      ".UNIF",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sony Playstation 2",
    folderNames: {
      emulationStation: ["ps2"],
    },
    extensions: [
      ".arcadedef",
      ".bin",
      ".BIN",
      ".chd",
      ".CHD",
      ".ciso",
      ".CISO",
      ".cso",
      ".CSO",
      ".dump",
      ".DUMP",
      ".elf",
      ".ELF",
      ".gz",
      ".GZ",
      ".m3u",
      ".M3U",
      ".mdf",
      ".MDF",
      ".img",
      ".IMG",
      ".iso",
      ".ISO",
      ".isz",
      ".ISZ",
      ".ngr",
      ".NRG",
    ],
  },
  {
    name: "Sony Playstation 3",
    folderNames: {
      emulationStation: ["ps3"],
    },
    extensions: [".desktop", ".ps3", ".PS3", ".ps3dir", ".PS3DIR"],
  },
  {
    name: "Sony Playstation 4",
    folderNames: {
      emulationStation: ["ps4"],
    },
    extensions: [".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Sony Playstation Portable",
    folderNames: {
      emulationStation: ["psp"],
    },
    extensions: [
      ".chd",
      ".CHD",
      ".cso",
      ".CSO",
      ".elf",
      ".ELF",
      ".iso",
      ".ISO",
      ".pbp",
      ".PBP",
      ".prx",
      ".PRX",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sony Playstation Vita",
    folderNames: {
      emulationStation: ["psvita"],
    },
    extensions: [".psvita"],
  },
  {
    name: "Sony Playstation",
    folderNames: {
      emulationStation: ["psx"],
      miyoo: ["PS"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".cbn",
      ".CBN",
      ".ccd",
      ".CCD",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".ecm",
      ".ECM",
      ".exe",
      ".EXE",
      ".img",
      ".IMG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".mdf",
      ".MDF",
      ".mds",
      ".MDS",
      ".minipsf",
      ".MINIPSF",
      ".pbp",
      ".PBP",
      ".psexe",
      ".PSEXE",
      ".psf",
      ".PSF",
      ".toc",
      ".TOC",
      ".z",
      ".Z",
      ".znx",
      ".ZNX",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega Saturn",
    folderNames: {
      emulationStation: ["saturn", "saturnjs"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".ccd",
      ".CCD",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".mds",
      ".MDS",
      ".toc",
      ".TOC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega 32X",
    folderNames: {
      emulationStation: ["sega32x", "sega32xjp", "sega32xna"],
      miyoo: ["THIRTYTWOX"],
    },
    extensions: [
      ".32x",
      ".32X",
      ".68k",
      ".68K",
      ".bin",
      ".BIN",
      ".cue",
      ".CUE",
      ".gen",
      ".GEN",
      ".iso",
      ".ISO",
      ".md",
      ".MD",
      ".smd",
      ".SMD",
      ".sms",
      ".SMS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega Genesis/Mega Drive",
    folderNames: {
      emulationStation: ["genesis", "megadrive", "megadrivejp"],
      miyoo: ["MD"],
    },
    extensions: [
      ".32x",
      ".32X",
      ".68k",
      ".68K",
      ".bin",
      ".BIN",
      ".bms",
      ".BMS",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".gen",
      ".GEN",
      ".gg",
      ".GG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".md",
      ".MD",
      ".mdx",
      ".MDX",
      ".sg",
      ".SG",
      ".sgd",
      ".SGD",
      ".smd",
      ".SMD",
      ".sms",
      ".SMS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega CD",
    folderNames: {
      emulationStation: ["megacd", "megacdjp", "segacd"],
      miyoo: ["segacd"],
    },
    extensions: [
      ".68k",
      ".68K",
      ".bin",
      ".BIN",
      ".bms",
      ".BMS",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".gen",
      ".GEN",
      ".gg",
      ".GG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".md",
      ".MD",
      ".mdx",
      ".MDX",
      ".sg",
      ".SG",
      ".sgd",
      ".SGD",
      ".smd",
      ".SMD",
      ".sms",
      ".SMS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega SG-1000",
    folderNames: {
      emulationStation: ["sg-1000"],
      miyoo: ["SEGASGONE"],
    },
    extensions: [
      ".68k",
      ".68K",
      ".bin",
      ".BIN",
      ".bms",
      ".BMS",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".gen",
      ".GEN",
      ".gg",
      ".GG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".md",
      ".MD",
      ".mdx",
      ".MDX",
      ".ri",
      ".RI",
      ".rom",
      ".ROM",
      ".sg",
      ".SG",
      ".sgd",
      ".SGD",
      ".smd",
      ".SMD",
      ".sms",
      ".SMS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "FinalBurn Alpha",
    folderNames: {
      emulationStation: ["fba"],
      miyoo: ["ARCADE"],
    },
    extensions: [".iso", ".ISO", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "FinalBurn Neo",
    folderNames: {
      emulationStation: ["fbneo"],
      miyoo: ["ARCADE"],
    },
    extensions: [".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Nintendo Famicom Disk System",
    folderNames: {
      emulationStation: ["fds"],
      miyoo: ["FDS"],
    },
    extensions: [
      ".nes",
      ".NES",
      ".fds",
      ".FDS",
      ".unf",
      ".UNF",
      ".UNIF",
      ".UNIF",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Fujitsu FM Towns",
    folderNames: {
      emulationStation: ["fmtowns"],
    },
    extensions: [
      ".cdr",
      ".CDR",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".gdi",
      ".GDI",
      ".iso",
      ".ISO",
    ],
  },
  {
    name: "Future Pinball",
    folderNames: {
      emulationStation: ["fpinball"],
    },
    extensions: [".fpt", ".FPT"],
  },
  {
    name: "Nintendo Game and Watch",
    folderNames: {
      emulationStation: ["gameandwatch"],
      miyoo: ["GW"],
    },
    extensions: [".mgw", ".MGW", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Hartung Game Master",
    folderNames: {
      emulationStation: ["gmaster"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Amstrad GX4000",
    folderNames: {
      emulationStation: ["gx4000"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".cdt",
      ".CDT",
      ".cpr",
      ".CPR",
      ".dsk",
      ".DSK",
      ".kcr",
      ".KCR",
      ".m3u",
      ".M3U",
      ".sna",
      ".SNA",
      ".tap",
      ".TAR",
      ".voc",
      ".VOC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "LCD Handheld Games",
    folderNames: {
      emulationStation: ["lcdgames"],
    },
    extensions: [".mgw", ".MGW", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "LowRes NX Fantasy Console",
    folderNames: {
      emulationStation: ["lowresnx"],
    },
    extensions: [".nx", ".NX"],
  },
  {
    name: "Lutro Game Engine",
    folderNames: {
      emulationStation: ["lutro"],
    },
    extensions: [
      ".lua",
      ".LUA",
      ".lutro",
      ".LUTRO",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Multiple Arcade Machine Emulator",
    folderNames: {
      emulationStation: ["mame"],
      miyoo: ["ARCADE"],
    },
    extensions: [
      ".cmd",
      ".CMD",
      ".desktop",
      ".sh",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "AdvanceMAME",
    folderNames: {
      emulationStation: ["mame-advmame"],
      miyoo: ["ARCADE"],
    },
    extensions: [".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Multi Emulator Super System",
    folderNames: {
      emulationStation: ["mess"],
    },
    extensions: [".chd", ".CHD", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Nintendo 3DS",
    folderNames: {
      emulationStation: ["n3ds"],
    },
    extensions: [
      ".3ds",
      ".3DS",
      ".3dsx",
      ".3DSX",
      ".app",
      ".APP",
      ".axf",
      ".AXF",
      ".cci",
      ".CCI",
      ".cxi",
      ".CXI",
      ".elf",
      ".ELF",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo DS",
    folderNames: {
      emulationStation: ["nds"],
      miyoo: ["DS"],
    },
    extensions: [
      ".app",
      ".APP",
      ".bin",
      ".BIN",
      ".nds",
      ".NDS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo 64",
    folderNames: {
      emulationStation: ["n64"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".d64",
      ".D64",
      ".n64",
      ".N64",
      ".ndd",
      ".NDD",
      ".u1",
      ".U1",
      ".v64",
      ".V64",
      ".z64",
      ".Z64",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo 64DD",
    folderNames: {
      emulationStation: ["n64dd"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".d64",
      ".D64",
      ".n64",
      ".N64",
      ".ndd",
      ".NDD",
      ".u1",
      ".U1",
      ".v64",
      ".V64",
      ".z64",
      ".Z64",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Wii",
    folderNames: {
      emulationStation: ["wii"],
    },
    extensions: [
      ".ciso",
      ".CISO",
      ".dff",
      ".DFF",
      ".dol",
      ".DOL",
      ".elf",
      ".ELF",
      ".gcm",
      ".GCM",
      ".gcz",
      ".GCZ",
      ".iso",
      ".ISO",
      ".json",
      ".JSON",
      ".m3u",
      ".M3U",
      ".rvz",
      ".RVZ",
      ".tgc",
      ".TGC",
      ".wad",
      ".WAD",
      ".wbfs",
      ".WBFS",
      ".wia",
      ".WIA",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Wii U",
    folderNames: {
      emulationStation: ["wiiu"],
    },
    extensions: [
      ".rpx",
      ".RPX",
      ".wua",
      ".WUA",
      ".wud",
      ".WUD",
      ".wux",
      ".WUX",
    ],
  },
  {
    name: "Microsoft Xbox",
    folderNames: {
      emulationStation: ["xbox"],
    },
    extensions: [".iso", ".ISO"],
  },
  {
    name: "Microsoft Xbox 360",
    folderNames: {
      emulationStation: ["xbox360"],
    },
    extensions: [".", ".desktop", ".iso", ".ISO", ".sh", ".xex", ".XEX"],
  },
  {
    name: "Sinclair ZX81",
    folderNames: {
      emulationStation: ["zx81"],
      miyoo: "ZXEIGHTYONE",
    },
    extensions: [".p", ".P", ".tzx", ".TZX", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Sinclair ZX Spectrum",
    folderNames: {
      emulationStation: ["zxspectrum"],
      miyoo: "ZXS",
    },
    extensions: [
      ".dsk",
      ".DSK",
      ".gz",
      ".GZ",
      ".img",
      ".IMG",
      ".mgt",
      ".MGT",
      ".rzx",
      ".RZX",
      ".scl",
      ".SCL",
      ".sh",
      ".SH",
      ".sna",
      ".SNA",
      ".szx",
      ".SZX",
      ".tap",
      ".TAP",
      ".trd",
      ".TRD",
      ".tzx",
      ".TZX",
      ".udi",
      ".UDI",
      ".z80",
      ".Z80",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sinclair ZX Spectrum Next",
    folderNames: {
      emulationStation: ["zxnext"],
    },
    extensions: [".nex", ".NEX", ".sna", ".SNA"],
  },
  {
    name: "Infocom Z-machine",
    folderNames: {
      emulationStation: ["zmachine"],
    },
    extensions: [
      ".dat",
      ".DAT",
      ".z1",
      ".Z1",
      ".z2",
      ".Z2",
      ".z3",
      ".Z3",
      ".z4",
      ".Z4",
      ".z5",
      ".Z5",
      ".z6",
      ".Z6",
      ".z7",
      ".Z7",
      ".z8",
      ".Z8",
      ".zlb",
      ".ZLB",
      ".zblorb",
      ".ZBLORB",
    ],
  },
  {
    name: "Sharp X68000",
    folderNames: {
      emulationStation: ["x68000"],
      miyoo: ["X68000"],
    },
    extensions: [
      ".2hd",
      ".2HD",
      ".88d",
      ".88D",
      ".cmd",
      ".CMD",
      ".d88",
      ".D88",
      ".dim",
      ".DIM",
      ".dup",
      ".DUP",
      ".hdf",
      ".HDF",
      ".hdm",
      ".HDM",
      ".img",
      ".IMG",
      ".m3u",
      ".M3U",
      ".xdf",
      ".XDF",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "WASM-4 Fantasy Console",
    folderNames: {
      emulationStation: ["wasm4"],
    },
    extensions: [".wasm", ".WASM"],
  },
  {
    name: "VTech V.Smile",
    folderNames: {
      emulationStation: ["vsmile"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Visual Pinball",
    folderNames: {
      emulationStation: ["vpinball"],
    },
    extensions: [".vpt", ".VPT", ".vpx", ".VPX"],
  },
  {
    name: "Solarus Game Engine",
    folderNames: {
      emulationStation: ["solarus"],
    },
    extensions: [".solarus"],
  },
  {
    name: "Spectravideo",
    folderNames: {
      emulationStation: ["spectravideo"],
    },
    extensions: [
      ".cas",
      ".CAS",
      ".col",
      ".COL",
      ".dsk",
      ".DSK",
      ".m3u",
      ".M3U",
      ".mx1",
      ".MX1",
      ".mx2",
      ".MX2",
      ".ri",
      ".RI",
      ".rom",
      ".ROM",
      ".sc",
      ".SC",
      ".sg",
      ".SG",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Bandai SuFami Turbo",
    folderNames: {
      emulationStation: ["sufami"],
    },
    extensions: [
      ".bml",
      ".BML",
      ".bs",
      ".BS",
      ".fig",
      ".FIG",
      ".sfc",
      ".SFC",
      ".smc",
      ".SMC",
      ".st",
      ".ST",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Epoch Super Cassette Vision",
    folderNames: {
      emulationStation: ["scv"],
    },
    extensions: [".0", ".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "ScummVM Game Engine",
    folderNames: {
      emulationStation: ["scummvm"],
      miyoo: ["SCUMMVM"],
    },
    extensions: [".scummvm", ".SCUMMVM", ".svm", ".SVM"],
  },
  {
    name: "Symbian",
    folderNames: {
      emulationStation: ["symbian"],
    },
    extensions: [".sis", ".SIS", ".sisx", ".SISX", ".symbian"],
  },
  {
    name: "Tano Dragon",
    folderNames: {
      emulationStation: ["tanodragon"],
    },
    extensions: [
      ".cas",
      ".CAS",
      ".ccc",
      ".CCC",
      ".dsk",
      ".DSK",
      ".rom",
      ".ROM",
    ],
  },
  {
    name: "MGT SAM Coupé",
    folderNames: {
      emulationStation: ["samcoupe"],
    },
    extensions: [
      ".dsk",
      ".DSK",
      ".mgt",
      ".MGT",
      ".sad",
      ".SAD",
      ".sbt",
      ".SBT",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Casio PV-1000",
    folderNames: {
      emulationStation: ["pv1000"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "IBM PC",
    folderNames: {
      emulationStation: ["pc"],
    },
    extensions: [
      ".bat",
      ".BAT",
      ".com",
      ".COM",
      ".conf",
      ".CONF",
      ".cue",
      ".CUE",
      ".dosz",
      ".DOSZ",
      ".exe",
      ".EXE",
      ".iso",
      ".ISO",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Palm OS",
    folderNames: {
      emulationStation: ["palm"],
    },
    extensions: [
      ".img",
      ".IMG",
      ".pqa",
      ".PQA",
      ".prc",
      ".PRC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Tangerine Computer Systems Oric",
    folderNames: {
      emulationStation: ["oric"],
    },
    extensions: [
      ".dsk",
      ".DSK",
      ".ort",
      ".ORT",
      ".tap",
      ".TAP",
      ".wav",
      ".WAV",
    ],
  },
  {
    name: "OpenBOR Game Engine",
    folderNames: {
      emulationStation: ["openbor"],
      miyoo: ["OPENBOR"],
    },
    extensions: [".AppImage"],
  },
  {
    name: "Sharp X1",
    folderNames: {
      emulationStation: ["x1"],
      miyoo: ["XONE"],
    },
    extensions: [
      ".2d",
      ".2D",
      ".2hd",
      ".2HD",
      ".88d",
      ".88D",
      ".cmd",
      ".CMD",
      ".d88",
      ".D88",
      ".dup",
      ".DUP",
      ".dx1",
      ".DX1",
      ".hdm",
      ".HDM",
      ".tap",
      ".TAP",
      ".tfd",
      ".TFD",
      ".xdf",
      ".XDF",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Bandai WonderSwan",
    folderNames: {
      emulationStation: ["wonderswan"],
      miyoo: ["WS"],
    },
    extensions: [".pc2", ".PC2", ".ws", ".WS", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Bandai WonderSwan Color",
    folderNames: {
      emulationStation: ["wonderswancolor"],
      miyoo: ["WS"],
    },
    extensions: [
      ".pc2",
      ".PC2",
      ".ws",
      ".WS",
      ".wsc",
      ".WSC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Virtual Boy",
    folderNames: {
      emulationStation: ["virtualboy"],
      miyoo: ["VB"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".vb",
      ".VB",
      ".vboy",
      ".VBOY",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Philips Videopac G7000",
    folderNames: {
      emulationStation: ["videopac"],
      miyoo: ["ODYSSEY"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Commodore VIC-20",
    folderNames: {
      emulationStation: ["vic20"],
      miyoo: ["COMMODORE"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".cmd",
      ".CMD",
      ".crt",
      ".CRT",
      ".d2m",
      ".D2M",
      ".d4m",
      ".D4M",
      ".d64",
      ".D64",
      ".d6z",
      ".D6Z",
      ".d71",
      ".D71",
      ".d7z",
      ".D7Z",
      ".d80",
      ".D80",
      ".d81",
      ".D81",
      ".d82",
      ".D82",
      ".d8z",
      ".D8Z",
      ".g41",
      ".G41",
      ".g4z",
      ".G4Z",
      ".g64",
      ".G64",
      ".g6z",
      ".G6Z",
      ".gz",
      ".GZ",
      ".lnx",
      ".LNX",
      ".m3u",
      ".M3U",
      ".nbz",
      ".NBZ",
      ".nib",
      ".NIB",
      ".p00",
      ".P00",
      ".prg",
      ".PRG",
      ".t64",
      ".T64",
      ".tap",
      ".TAP",
      ".vfl",
      ".VFL",
      ".vsf",
      ".VSF",
      ".x64",
      ".X64",
      ".x6z",
      ".X6Z",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Smith Engineering Vectrex",
    folderNames: {
      emulationStation: ["vectrex"],
      miyoo: ["VECTREX"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".gam",
      ".GAM",
      ".vc",
      ".VC",
      ".vec",
      ".VEC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Uzebox Open Source Console",
    folderNames: {
      emulationStation: ["uzebox"],
      miyoo: ["UZEBOX"],
    },
    extensions: [".uze", ".UZE", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Tandy TRS-80",
    folderNames: {
      emulationStation: ["trs-80"],
    },
    extensions: [".cmd", ".CMD", ".dsk", ".DSK"],
  },
  {
    name: "Thomson TO8",
    folderNames: {
      emulationStation: ["to8"],
    },
    extensions: [
      ".fd",
      ".FD",
      ".k7",
      ".K7",
      ".m5",
      ".M5",
      ".m7",
      ".M7",
      ".rom",
      ".ROM",
      ".sap",
      ".SAP",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "TIC-80 Game Engine",
    folderNames: {
      emulationStation: ["tic80"],
      miyoo: ["TIC"],
    },
    extensions: [".tic", ".TIC"],
  },
  {
    name: "Texas Instruments TI-99",
    folderNames: {
      emulationStation: ["ti99"],
    },
    extensions: [".rpk", ".RPK", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Nintendo Switch",
    folderNames: {
      emulationStation: ["switch"],
    },
    extensions: [
      ".nca",
      ".NCA",
      ".nro",
      ".NRO",
      ".nso",
      ".NSO",
      ".nsp",
      ".NSP",
      ".xci",
      ".XCI",
    ],
  },
  {
    name: "Super Nintendo",
    folderNames: {
      emulationStation: ["snes", "snesna", "sfc"],
      miyoo: ["SFC"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".bml",
      ".BML",
      ".bs",
      ".BS",
      ".bsx",
      ".BSX",
      ".dx2",
      ".DX2",
      ".fig",
      ".FIG",
      ".gd3",
      ".GD3",
      ".gd7",
      ".GD7",
      ".mgd",
      ".MGD",
      ".sfc",
      ".SFC",
      ".smc",
      ".SMC",
      ".st",
      ".ST",
      ".swc",
      ".SWC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "NEC TurboGrafx-CD",
    folderNames: {
      emulationStation: ["tg-cd"],
      miyoo: ["PCECD"],
    },
    extensions: [
      ".ccd",
      ".CCD",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".img",
      ".IMG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".pce",
      ".PCE",
      ".sgx",
      ".SGX",
      ".toc",
      ".TOC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Watara Supervision",
    folderNames: {
      emulationStation: ["supervision"],
      miyoo: ["SUPERVISION"],
    },
    extensions: [".bin", ".BIN", ".sv", ".SV", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "NEC SuperGrafx",
    folderNames: {
      emulationStation: ["supergrafx"],
      miyoo: ["SGFX"],
    },
    extensions: [
      ".ccd",
      ".CCD",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".pce",
      ".PCE",
      ".sgx",
      ".SGX",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "NEC PC-8800 Series",
    folderNames: {
      emulationStation: ["pc88"],
    },
    extensions: [
      ".88d",
      ".88D",
      ".cmt",
      ".CMT",
      ".d88",
      ".D88",
      ".m3u",
      ".M3U",
      ".t88",
      ".T88",
      ".u88",
      ".U88",
    ],
  },
  {
    name: "NEC PC-9800 Series",
    folderNames: {
      emulationStation: ["pc98"],
    },
    extensions: [
      ".2hd",
      ".2HD",
      ".88d",
      ".88D",
      ".98d",
      ".98D",
      ".d88",
      ".D88",
      ".d98",
      ".D98",
      ".cmd",
      ".CMD",
      ".dup",
      ".DUP",
      ".fdd",
      ".FDD",
      ".fdi",
      ".FDI",
      ".hdd",
      ".HDD",
      ".hdi",
      ".HDI",
      ".hdm",
      ".HDM",
      ".hdn",
      ".HDN",
      ".m3u",
      ".M3U",
      ".nhd",
      ".NHD",
      ".tfd",
      ".TFD",
      ".thd",
      ".THD",
      ".xdf",
      ".XDF",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "PICO-8 Fantasy Console",
    folderNames: {
      emulationStation: ["pico8"],
      miyoo: ["PICO"],
    },
    extensions: [".p8", ".P8", ".png", ".PNG"],
  },
  {
    name: "Nintendo Pokémon Mini",
    folderNames: {
      emulationStation: ["pokemini"],
      miyoo: ["POKE"],
    },
    extensions: [".min", ".MIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Tiger Electronics Game.com",
    folderNames: {
      emulationStation: ["gamecom"],
    },
    extensions: [".tgc", ".TGC", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Sega Game Gear",
    folderNames: {
      emulationStation: ["gamegear"],
      miyoo: ["GG"],
    },
    extensions: [
      ".68k",
      ".68K",
      ".bin",
      ".BIN",
      ".bms",
      ".BMS",
      ".chd",
      ".CHD",
      ".col",
      ".COL",
      ".cue",
      ".CUE",
      ".gen",
      ".GEN",
      ".gg",
      ".GG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".md",
      ".MD",
      ".mdx",
      ".MDX",
      ".rom",
      ".ROM",
      ".sg",
      ".SG",
      ".sgd",
      ".SGD",
      ".smd",
      ".SMD",
      ".sms",
      ".SMS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Game Boy",
    folderNames: {
      emulationStation: ["gb"],
      miyoo: ["GB"],
    },
    extensions: [
      ".bs",
      ".BS",
      ".cgb",
      ".CGB",
      ".dmg",
      ".DMG",
      ".gb",
      ".GB",
      ".gbc",
      ".GBC",
      ".sgb",
      ".SGB",
      ".sfc",
      ".SFC",
      ".smc",
      ".SMC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Game Boy Advance",
    folderNames: {
      emulationStation: ["gba"],
      miyoo: ["GBA"],
    },
    extensions: [
      ".agb",
      ".AGB",
      ".bin",
      ".BIN",
      ".cgb",
      ".CGB",
      ".dmg",
      ".DMG",
      ".gb",
      ".GB",
      ".gba",
      ".GBA",
      ".gbc",
      ".GBC",
      ".sgb",
      ".SGB",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Game Boy Color",
    folderNames: {
      emulationStation: ["gbc"],
      miyoo: ["GBC"],
    },
    extensions: [
      ".bs",
      ".BS",
      ".cgb",
      ".CGB",
      ".dmg",
      ".DMG",
      ".gb",
      ".GB",
      ".gbc",
      ".GBC",
      ".sgb",
      ".SGB",
      ".sfc",
      ".SFC",
      ".smc",
      ".SMC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo GameCube",
    folderNames: {
      emulationStation: ["gc"],
    },
    extensions: [
      ".ciso",
      ".CISO",
      ".dff",
      ".DFF",
      ".dol",
      ".DOL",
      ".elf",
      ".ELF",
      ".gcm",
      ".GCM",
      ".gcz",
      ".GCZ",
      ".iso",
      ".ISO",
      ".json",
      ".JSON",
      ".m3u",
      ".M3U",
      ".rvz",
      ".RVZ",
      ".tgc",
      ".TGC",
      ".wad",
      ".WAD",
      ".wbfs",
      ".WBFS",
      ".wia",
      ".WIA",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Mattel Electronics Intellivision",
    folderNames: {
      emulationStation: ["intellivision"],
      miyoo: ["INTELLIVISION"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".int",
      ".INT",
      ".rom",
      ".ROM",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega Master System",
    folderNames: {
      emulationStation: ["mastersystem"],
      miyoo: ["MS"],
    },
    extensions: [
      ".68k",
      ".68K",
      ".bin",
      ".BIN",
      ".bms",
      ".BMS",
      ".chd",
      ".CHD",
      ".col",
      ".COL",
      ".cue",
      ".CUE",
      ".gen",
      ".GEN",
      ".gg",
      ".GG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".md",
      ".MD",
      ".mdx",
      ".MDX",
      ".rom",
      ".ROM",
      ".sg",
      ".SG",
      ".sgd",
      ".SGD",
      ".smd",
      ".SMD",
      ".sms",
      ".SMS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega Model 2",
    folderNames: {
      emulationStation: ["model2"],
    },
    extensions: [".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Sega Model 3",
    folderNames: {
      emulationStation: ["model3"],
    },
    extensions: [".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Thomson MO/TO Series",
    folderNames: {
      emulationStation: ["moto"],
    },
    extensions: [
      ".fd",
      ".FD",
      ".k7",
      ".K7",
      ".m5",
      ".M5",
      ".m7",
      ".M7",
      ".rom",
      ".ROM",
      ".sap",
      ".SAP",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "MSX",
    folderNames: {
      emulationStation: ["msx"],
      miyoo: ["MSX"],
    },
    extensions: [
      ".cas",
      ".CAS",
      ".col",
      ".COL",
      ".di1",
      ".DI1",
      ".di2",
      ".DI2",
      ".dmk",
      ".DMK",
      ".dsk",
      ".DSK",
      ".fd1",
      ".FD1",
      ".fd2",
      ".FD2",
      ".m3u",
      ".M3U",
      ".mx1",
      ".MX1",
      ".mx2",
      ".MX2",
      ".ogv",
      ".OGV",
      ".ri",
      ".RI",
      ".rom",
      ".ROM",
      ".sc",
      ".SC",
      ".sg",
      ".SG",
      ".wav",
      ".WAV",
      ".xsa",
      ".XSA",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "MSX1",
    folderNames: {
      emulationStation: ["msx1"],
      miyoo: ["MSX"],
    },
    extensions: [
      ".cas",
      ".CAS",
      ".col",
      ".COL",
      ".di1",
      ".DI1",
      ".di2",
      ".DI2",
      ".dmk",
      ".DMK",
      ".dsk",
      ".DSK",
      ".fd1",
      ".FD1",
      ".fd2",
      ".FD2",
      ".m3u",
      ".M3U",
      ".mx1",
      ".MX1",
      ".mx2",
      ".MX2",
      ".ogv",
      ".OGV",
      ".ri",
      ".RI",
      ".rom",
      ".ROM",
      ".sc",
      ".SC",
      ".sg",
      ".SG",
      ".wav",
      ".WAV",
      ".xsa",
      ".XSA",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "MSX2",
    folderNames: {
      emulationStation: ["msx2"],
      miyoo: ["MSX"],
    },
    extensions: [
      ".cas",
      ".CAS",
      ".col",
      ".COL",
      ".di1",
      ".DI1",
      ".di2",
      ".DI2",
      ".dmk",
      ".DMK",
      ".dsk",
      ".DSK",
      ".fd1",
      ".FD1",
      ".fd2",
      ".FD2",
      ".m3u",
      ".M3U",
      ".mx1",
      ".MX1",
      ".mx2",
      ".MX2",
      ".ogv",
      ".OGV",
      ".ri",
      ".RI",
      ".rom",
      ".ROM",
      ".sc",
      ".SC",
      ".sg",
      ".SG",
      ".wav",
      ".WAV",
      ".xsa",
      ".XSA",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Creatronic Mega Duck",
    folderNames: {
      emulationStation: ["megaduck"],
      miyoo: ["MEGADUCK"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Apple Macintosh",
    folderNames: {
      emulationStation: ["macintosh"],
    },
    extensions: [".dsk", ".DSK", ".game", ".GAME"],
  },
  {
    name: "MSX Turbo R",
    folderNames: {
      emulationStation: ["msxturbor"],
    },
    extensions: [
      ".cas",
      ".CAS",
      ".col",
      ".COL",
      ".di1",
      ".DI1",
      ".di2",
      ".DI2",
      ".dmk",
      ".DMK",
      ".dsk",
      ".DSK",
      ".fd1",
      ".FD1",
      ".fd2",
      ".FD2",
      ".m3u",
      ".M3U",
      ".mx1",
      ".MX1",
      ".mx2",
      ".MX2",
      ".ogv",
      ".OGV",
      ".ri",
      ".RI",
      ".rom",
      ".ROM",
      ".sc",
      ".SC",
      ".sg",
      ".SG",
      ".wav",
      ".WAV",
      ".xsa",
      ".XSA",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "M.U.G.E.N Game Engine",
    folderNames: {
      emulationStation: ["mugen"],
    },
    extensions: [".mugen"],
  },
  {
    name: "Othello Multivision",
    folderNames: {
      emulationStation: ["multivision"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".gg",
      ".GG",
      ".rom",
      ".ROM",
      ".sg",
      ".SG",
      ".sms",
      ".SMS",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "NEC TurboGrafx-16",
    folderNames: {
      emulationStation: ["tg16", "pcengine"],
      miyoo: ["PCE"],
    },
    extensions: [
      ".ccd",
      ".CCD",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".img",
      ".IMG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".pce",
      ".PCE",
      ".sgx",
      ".SGX",
      ".toc",
      ".TOC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "NEC TurboGrafx CD",
    folderNames: {
      emulationStation: ["pcenginecd"],
      miyoo: ["PCECD"],
    },
    extensions: [
      ".ccd",
      ".CCD",
      ".chd",
      ".CHD",
      ".cue",
      ".CUE",
      ".img",
      ".IMG",
      ".iso",
      ".ISO",
      ".m3u",
      ".M3U",
      ".pce",
      ".PCE",
      ".sgx",
      ".SGX",
      ".toc",
      ".TOC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega NAOMI",
    folderNames: {
      emulationStation: ["naomi"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".dat",
      ".DAT",
      ".elf",
      ".ELF",
      ".lst",
      ".LST",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega NAOMI 2",
    folderNames: {
      emulationStation: ["naomi2"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".dat",
      ".DAT",
      ".elf",
      ".ELF",
      ".lst",
      ".LST",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Sega NAOMI CD-ROM",
    folderNames: {
      emulationStation: ["naomigd"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".dat",
      ".DAT",
      ".elf",
      ".ELF",
      ".lst",
      ".LST",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "SNK Neo Geo",
    folderNames: {
      emulationStation: ["neogeo"],
      miyoo: ["NEOGEO"],
    },
    extensions: [".7z", ".7Z", ".zip", ".ZIP"],
  },

  {
    name: "SNK Neo Geo",
    folderNames: {
      emulationStation: ["supracan"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Funtech Super A'Can",
    folderNames: {
      emulationStation: ["neogeocd", "neogeocdjp"],
      miyoo: ["NEOCD"],
    },
    extensions: [".chd", ".CHD", ".cue", ".CUE"],
  },
  {
    name: "SNK Neo Geo Pocket",
    folderNames: {
      emulationStation: ["ngp"],
      miyoo: ["NGP"],
    },
    extensions: [
      ".ngc",
      ".NGC",
      ".ngp",
      ".NGP",
      ".ngpc",
      ".NGPC",
      ".npc",
      ".NPC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "SNK Neo Geo Pocket Color",
    folderNames: {
      emulationStation: ["ngpc"],
      miyoo: ["NGP"],
    },
    extensions: [
      ".ngc",
      ".NGC",
      ".ngp",
      ".NGP",
      ".ngpc",
      ".NGPC",
      ".npc",
      ".NPC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nokia NGage",
    folderNames: {
      emulationStation: ["ngage"],
    },
    extensions: [".ngage", ".zip", ".ZIP"],
  },
  {
    name: "Magnavox Odyssey2",
    folderNames: {
      emulationStation: ["odyssey2"],
      miyoo: ["ODYSSEY"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "NEC PC-FX",
    folderNames: {
      emulationStation: ["pcfx"],
      miyoo: ["PCFX"],
    },
    extensions: [
      ".ccd",
      ".CCD",
      ".chd",
      ".CHD",
      ".cue",
      "CUE",
      ".m3u",
      ".M3U",
      ".toc",
      ".TOC",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Satellaview",
    folderNames: {
      emulationStation: ["satellaview"],
      miyoo: ["SATELLAVIEW"],
    },
    extensions: [
      ".bml",
      ".BML",
      ".bs",
      ".BS",
      ".fig",
      ".FIG",
      ".sfc",
      ".SFC",
      ".smc",
      ".SMC",
      ".swc",
      ".SWC",
      ".st",
      ".ST",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Nintendo Super Game Boy",
    folderNames: {
      emulationStation: ["sgb"],
      miyoo: ["SGB"],
    },
    extensions: [
      ".gb",
      ".GB",
      ".gbc",
      ".GBC",
      ".sgb",
      ".SGB",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Taito Type X",
    folderNames: {
      emulationStation: ["type-x"],
    },
    extensions: [".AppImage", ".desktop", ".exe", ".EXE", ".sh"],
  },
  {
    folderNames: {
      emulationStation: ["triforce"],
    },
    extensions: [
      ".ciso",
      ".CISO",
      ".dff",
      ".DFF",
      ".dol",
      ".DOL",
      ".elf",
      ".ELF",
      ".gcm",
      ".GCM",
      ".gcz",
      ".GCZ",
      ".iso",
      ".ISO",
      ".json",
      ".JSON",
      ".m3u",
      ".M3U",
      ".rvz",
      ".RVZ",
      ".tgc",
      ".TGC",
      ".wad",
      ".WAD",
      ".wbfs",
      ".WBFS",
      ".wia",
      ".WIA",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },

  {
    name: "Ports",
    folderNames: {
      emulationStation: ["ports"],
    },
    extensions: [
      ".AppImage",
      ".desktop",
      ".exe",
      ".EXE",
      ".game",
      ".GAME",
      ".phd",
      ".PHD",
      ".psx",
      ".PSX",
      ".sh",
    ],
  },
  {
    name: "Commodore Plus/4",
    folderNames: {
      emulationStation: ["plus4"],
    },
    extensions: [
      ".bin",
      ".BIN",
      ".cmd",
      ".CMD",
      ".crt",
      ".CRT",
      ".d2m",
      ".D2M",
      ".d4m",
      ".D4M",
      ".d64",
      ".D64",
      ".d6z",
      ".D6Z",
      ".d71",
      ".D71",
      ".d7z",
      ".D7Z",
      ".d80",
      ".D80",
      ".d81",
      ".D81",
      ".d82",
      ".D82",
      ".d8z",
      ".D8Z",
      ".g41",
      ".G41",
      ".g4z",
      ".G4Z",
      ".g64",
      ".G64",
      ".g6z",
      ".G6Z",
      ".gz",
      ".GZ",
      ".lnx",
      ".LNX",
      ".m3u",
      ".M3U",
      ".nbz",
      ".NBZ",
      ".nib",
      ".NIB",
      ".p00",
      ".P00",
      ".prg",
      ".PRG",
      ".t64",
      ".T64",
      ".tap",
      ".TAP",
      ".vfl",
      ".VFL",
      ".vsf",
      ".VSF",
      ".x64",
      ".X64",
      ".x6z",
      ".X6Z",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Quake",
    folderNames: {
      emulationStation: ["quake"],
    },
    extensions: [".desktop", ".pak", ".PAK", ".pk3", ".PK3", ".sh"],
  },
  {
    name: "Sega Titan Video Game System",
    folderNames: {
      emulationStation: ["stv"],
    },
    extensions: [".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Java 2 Micro Edition (J2ME)",
    folderNames: {
      emulationStation: ["j2me"],
    },
    extensions: [".jar", ".JAR", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Bit Corporation Gamate",
    folderNames: {
      emulationStation: ["gamate"],
    },
    extensions: [".bin", ".BIN", ".7z", ".7Z", ".zip", ".ZIP"],
  },
  {
    name: "Fujitsu FM-7",
    folderNames: {
      emulationStation: ["fm7"],
    },
    extensions: [
      ".1dd",
      ".1DD",
      ".cqi",
      ".CQI",
      ".cqm",
      ".CQM",
      ".d77",
      ".D77",
      ".d88",
      ".D88",
      ".dfi",
      ".DFI",
      ".dsk",
      ".DSK",
      ".hfe",
      ".HFE",
      ".imd",
      ".IMD",
      ".mfi",
      ".MFI",
      ".mfm",
      ".MFM",
      ".t77",
      ".T77",
      ".td0",
      ".TD0",
      ".wav",
      ".WAV",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },

  {
    name: "Acorn Electron",
    folderNames: {
      emulationStation: ["electron"],
    },
    extensions: [
      ".1dd",
      ".1DD",
      ".adf",
      ".ADF",
      ".adl",
      ".ADL",
      ".adm",
      ".ADM",
      ".ads",
      ".ADS",
      ".bbc",
      ".BBC",
      ".bin",
      ".BIN",
      ".cqi",
      ".CQI",
      ".cqm",
      ".CQM",
      ".csw",
      ".CSW",
      ".d77",
      ".D77",
      ".d88",
      ".D88",
      ".dfi",
      ".DFI",
      ".dsd",
      ".DSD",
      ".dsk",
      ".DSK",
      ".hfe",
      ".HFE",
      ".imd",
      ".IMD",
      ".img",
      ".IMG",
      ".mfi",
      ".MFI",
      ".mfm",
      ".MFM",
      ".rom",
      ".ROM",
      ".ssd",
      ".SSD",
      ".td0",
      ".TD0",
      ".uef",
      ".UEF",
      ".wav",
      ".WAV",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Acorn Archimedes",
    folderNames: {
      emulationStation: ["archimedes"],
    },
    extensions: [
      ".1dd",
      ".1DD",
      ".360",
      ".adf",
      ".ADF",
      ".adl",
      ".ADL",
      ".adm",
      ".ADM",
      ".ads",
      ".ADS",
      ".apd",
      ".APD",
      ".bbc",
      ".BBC",
      ".chd",
      ".CHD",
      ".cqi",
      ".CQI",
      ".cqm",
      ".CQM",
      ".d77",
      ".D77",
      ".d88",
      ".D88",
      ".dfi",
      ".DFI",
      ".dsd",
      ".DSD",
      ".dsk",
      ".DSK",
      ".hfe",
      ".HFE",
      ".ima",
      ".IMA",
      ".imd",
      ".IMD",
      ".img",
      ".IMG",
      ".ipf",
      ".IPF",
      ".jfd",
      ".JFD",
      ".mfi",
      ".MFI",
      ".mfm",
      ".MFM",
      ".msa",
      ".MSA",
      ".ssd",
      ".SSD",
      ".st",
      ".ST",
      ".td0",
      ".TD0",
      ".ufi",
      ".UFI",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
  {
    name: "Coleco Adam",
    folderNames: {
      emulationStation: ["adam"],
    },
    extensions: [
      ".1dd",
      ".1DD",
      ".bin",
      ".BIN",
      ".col",
      ".COL",
      ".cqi",
      ".CQI",
      ".cqm",
      ".CQM",
      ".d77",
      ".D77",
      ".d88",
      ".D88",
      ".ddp",
      ".DDP",
      ".dfi",
      ".DFI",
      ".dsk",
      ".DSK",
      ".hfe",
      ".HFE",
      ".imd",
      ".IMD",
      ".mfi",
      ".MFI",
      ".mfm",
      ".MFM",
      ".rom",
      ".ROM",
      ".td0",
      ".TD0",
      ".wav",
      ".WAV",
      ".7z",
      ".7Z",
      ".zip",
      ".ZIP",
    ],
  },
];
